spring:
  cloud:
    gateway:
      routes:
        # Route for Admin Management Service
        - id: admin-service
          uri: http://localhost:8082  # Assuming the Admin Management Service runs on port 8081
          predicates:
            - Path=/api/admin/**
          filters:
            - RewritePath=/api/admin/(?<segment>.*), /api/${segment}

        # Route for Book Service
        - id: book-service
          uri: http://localhost:8083  # Assuming the Book Service runs on port 8083
          predicates:
            - Path=/api/books/**
          filters:
            - RewritePath=/api/books/(?<segment>.*), /api/${segment}

        # Route for Ontology Service (if queries are routed here)
        - id: ontology-service
          uri: http://localhost:8084  # Assuming the Ontology Service runs on port 8083
          predicates:
            - Path=/api/ontology/**
          filters:
            - RewritePath=/api/ontology/(?<segment>.*), /api/${segment}

      default-filters:
        - name: DedupeResponseHeader
          args:
            name: Access-Control-Allow-Origin, Access-Control-Allow-Credentials
            strategy: RETAIN_UNIQUE  # Or RETAIN_FIRST / RETAIN_LAST
  server:
    port: 8081  # The API Gateway listens on port 8080

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
